services:
  - type: web
    name: finsight-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./finsight.db
      - key: NVIDIA_API_KEY
        value: "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"
      - key: PORT
        value: 10000
